lenguage: java
jdk: oraclejdk8 



deploy:
  provider: script
  api_key: "8a793fc0fec89b26b4c9f40485a8f12814e1e833"
  file: "Simple-Java-Calculator-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  draft: true
  script: mvn clean package