lenguage: java
jdk: oraclejdk8 

script: mvn clean package    

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $git_toks
  file: "/home/travis/build/mokbor/Simple-Java-Calculator/target/Simple-Java-Calculator-0.0.1-SNAPSHOT.jar"
  draft: true
  all_branches: true
  on:
    tags: false
    
