lenguage: java
jdk: oraclejdk8 




deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "d42a95d8b461f9bc082ae0750517fb88408ad250"
  file:
    - "Simple-Java-Calculator-0.0.1-SNAPSHOT.jar"
  on:
    tags: false
    all_branches: true
    repo: mokbor/Simple-Java-Calculator

branches:
  except:
    - /^*-v[0-9]/

script: 
    - mvn clean package